[build]
builder = "dockerfile"

[deploy]
startCommand = "./docker-entrypoint.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "biology-rag"

[services.variables]
NODE_ENV = "production"
PORT = "3001"
FRONTEND_PORT = "8080"
