services:
  - type: web
    name: biology-rag
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    region: oregon
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_PORT
        value: 8080
    disk:
      name: biology-rag-disk
      mountPath: /app/data
      sizeGB: 10
