name: biology-rag-system
services:
- name: biology-rag
  source_dir: /
  github:
    repo: your-username/biologyVectorDatabase
    branch: main
    deploy_on_push: true
  run_command: ./docker-entrypoint.sh
  environment_slug: docker
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: FRONTEND_PORT
    value: "8080"
